"""adjuntar documentos de admision

Revision ID: 20b905cd940e
Revises: 919d280ab368
Create Date: 2026-09-08 21:41:49.351511

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20b905cd940e"
down_revision: str | Sequence[str] | None = "919d280ab368"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documento_solicitud", sa.Column("tipo_contenido", sa.String(), nullable=True))
    op.add_column("documento_solicitud", sa.Column("tamanio", sa.Integer(), nullable=True))
    op.add_column("documento_solicitud", sa.Column("contenido", sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documento_solicitud", "contenido")
    op.drop_column("documento_solicitud", "tamanio")
    op.drop_column("documento_solicitud", "tipo_contenido")
    # ### end Alembic commands ###
