"""agregar unicidad a legajo de alumno

Revision ID: 2abdec1fcb72
Revises: ab2435963cc1
Create Date: 2026-09-07 00:18:17.624561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2abdec1fcb72'
down_revision: Union[str, Sequence[str], None] = 'ab2435963cc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_alumno_numero_legajo', 'alumno', ['numero_legajo'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_alumno_numero_legajo', 'alumno', type_='unique')
    # ### end Alembic commands ###
