"""agregar ejecucion automatica de facturacion

Revision ID: 70743ef2902c
Revises: 7df41b8dcf59
Create Date: 2026-08-31 16:47:25.740661

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "70743ef2902c"
down_revision: str | Sequence[str] | None = "7df41b8dcf59"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ejecucion_facturacion_regla",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ejecucion_facturacion_id", sa.Uuid(), nullable=False),
        sa.Column("regla_facturacion_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ejecucion_facturacion_id"],
            ["ejecucion_facturacion.id"],
        ),
        sa.ForeignKeyConstraint(
            ["regla_facturacion_id"],
            ["regla_facturacion.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "ejecucion_facturacion_id",
            "regla_facturacion_id",
            name="uq_ejecucion_facturacion_regla",
        ),
    )
    op.create_index(
        "ix_ejecucion_facturacion_regla_regla",
        "ejecucion_facturacion_regla",
        ["regla_facturacion_id"],
        unique=False,
    )
    op.add_column(
        "ejecucion_facturacion",
        sa.Column("origen", sa.String(), server_default="manual", nullable=False),
    )
    op.add_column(
        "ejecucion_facturacion",
        sa.Column("estado", sa.String(), server_default="exitosa", nullable=False),
    )
    op.add_column("ejecucion_facturacion", sa.Column("error_detalle", sa.Text(), nullable=True))
    op.create_check_constraint(
        "ck_ejecucion_facturacion_estado",
        "ejecucion_facturacion",
        "estado IN ('exitosa', 'parcial', 'fallida')",
    )
    op.create_check_constraint(
        "ck_ejecucion_facturacion_origen",
        "ejecucion_facturacion",
        "origen IN ('manual', 'automatica')",
    )
    op.add_column(
        "regla_facturacion",
        sa.Column("modo_generacion", sa.String(), server_default="manual", nullable=False),
    )
    op.add_column("regla_facturacion", sa.Column("dia_generacion", sa.Integer(), nullable=True))
    op.create_check_constraint(
        "ck_regla_facturacion_modo_generacion",
        "regla_facturacion",
        "modo_generacion IN ('manual', 'automatica')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_regla_facturacion_modo_generacion", "regla_facturacion", type_="check")
    op.drop_column("regla_facturacion", "dia_generacion")
    op.drop_column("regla_facturacion", "modo_generacion")
    op.drop_constraint("ck_ejecucion_facturacion_origen", "ejecucion_facturacion", type_="check")
    op.drop_constraint("ck_ejecucion_facturacion_estado", "ejecucion_facturacion", type_="check")
    op.drop_column("ejecucion_facturacion", "error_detalle")
    op.drop_column("ejecucion_facturacion", "estado")
    op.drop_column("ejecucion_facturacion", "origen")
    op.drop_index("ix_ejecucion_facturacion_regla_regla", table_name="ejecucion_facturacion_regla")
    op.drop_table("ejecucion_facturacion_regla")
    # ### end Alembic commands ###
