"""modelado completo de base de datos - 54 tablas

Revision ID: 7ba0cd6025cc
Revises: 
Create Date: 2026-08-27 15:48:40.381436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ba0cd6025cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concepto_cobro',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metodo_pago',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('requiere_comprobante', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motivo_justificacion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nivel_educativo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificacion_template',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('asunto', sa.String(), nullable=False),
    sa.Column('cuerpo', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permiso',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('modulo', sa.String(), nullable=False),
    sa.Column('accion', sa.String(), nullable=False),
    sa.Column('tipo_informacion', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persona',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('dni', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('sexo', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producto_servicio',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('unidad', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tipo IN ('producto', 'servicio')", name='ck_producto_servicio_tipo'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proveedor',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado IN ('activo', 'inactivo')", name='ck_proveedor_estado'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rol',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_evento',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alumno',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('numero_legajo', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('persona_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("estado IN ('activo', 'inactivo', 'egresado')", name='ck_alumno_estado'),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anio',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('nivel_educativo_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['nivel_educativo_id'], ['nivel_educativo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campo_evento',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre_interno', sa.String(), nullable=False),
    sa.Column('etiqueta', sa.String(), nullable=False),
    sa.Column('tipo_dato', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('tipo_evento_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("tipo_dato IN ('numero', 'texto', 'fecha')", name='ck_campo_evento_tipo_dato'),
    sa.ForeignKeyConstraint(['tipo_evento_id'], ['tipo_evento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('docente',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('legajo', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('persona_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('familia',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('estado_deuda', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('persona_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("estado_deuda IN ('al_dia', 'con_deuda', 'en_mora')", name='ck_familia_estado_deuda'),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orden_compra',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('proveedor_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("estado IN ('emitida', 'recibida', 'cancelada')", name='ck_orden_compra_estado'),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('precio_producto',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vigencia_desde', sa.Date(), nullable=False),
    sa.Column('vigencia_hasta', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('producto_servicio_id', sa.Uuid(), nullable=False),
    sa.Column('proveedor_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['producto_servicio_id'], ['producto_servicio.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producto_proveedor',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('producto_servicio_id', sa.Uuid(), nullable=False),
    sa.Column('proveedor_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['producto_servicio_id'], ['producto_servicio.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regla_penalidad',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('desde_dia_vencido', sa.Integer(), nullable=False),
    sa.Column('hasta_dia_vencido', sa.Integer(), nullable=True),
    sa.Column('porcentaje', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('concepto_cobro_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['concepto_cobro_id'], ['concepto_cobro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rol_permiso',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rol_id', sa.Uuid(), nullable=False),
    sa.Column('permiso_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permiso.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('auth_provider', sa.String(), nullable=False),
    sa.Column('provider_subject', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('persona_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("auth_provider IN ('google', 'local')", name='ck_usuario_auth_provider'),
    sa.CheckConstraint("estado IN ('activo', 'inactivo')", name='ck_usuario_estado'),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_rule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('condicion', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tipo_accion', sa.String(), nullable=False),
    sa.Column('accion_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('criticidad', sa.String(), nullable=False),
    sa.Column('requiere_aprobacion_humana', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('tipo_evento_id', sa.Uuid(), nullable=False),
    sa.Column('notificacion_template_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("criticidad IN ('baja', 'media', 'alta', 'critica')", name='ck_workflow_rule_criticidad'),
    sa.CheckConstraint("tipo_accion IN ('notificar', 'alerta_interna', 'cambiar_estado', 'crear_tarea', 'generar_cargo', 'aplicar_vencimiento', 'aplicar_penalidad', 'registrar_pago', 'registrar_rechazo', 'actualizar_cuenta_corriente', 'generar_recordatorio', 'escalar_caso', 'crear_registro_relacionado', 'generar_orden_compra', 'generar_comunicacion')", name='ck_workflow_rule_tipo_accion'),
    sa.ForeignKeyConstraint(['notificacion_template_id'], ['notificacion_template.id'], ),
    sa.ForeignKeyConstraint(['tipo_evento_id'], ['tipo_evento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entidad', sa.String(), nullable=False),
    sa.Column('entidad_id', sa.Uuid(), nullable=False),
    sa.Column('campo', sa.String(), nullable=False),
    sa.Column('valor_anterior', sa.String(), nullable=True),
    sa.Column('valor_nuevo', sa.String(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_entidad_entidad_id_fecha', 'audit_log', ['entidad', 'entidad_id', 'fecha'], unique=False)
    op.create_table('cuenta_corriente',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('alumno_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumno.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alumno_id')
    )
    op.create_table('division',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('anio_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['anio_id'], ['anio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_tipo', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('entidad', sa.String(), nullable=False),
    sa.Column('entidad_id', sa.Uuid(), nullable=False),
    sa.Column('tipo_evento_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("actor_tipo IN ('usuario', 'sistema')", name='ck_event_log_actor_tipo'),
    sa.CheckConstraint("estado IN ('pendiente', 'procesado', 'fallido')", name='ck_event_log_estado'),
    sa.ForeignKeyConstraint(['tipo_evento_id'], ['tipo_evento.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_log_estado_timestamp', 'event_log', ['estado', 'timestamp'], unique=False)
    op.create_table('excepcion_vencimiento',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fecha_vencimiento_excepcional', sa.Date(), nullable=False),
    sa.Column('motivo', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('familia_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['familia_id'], ['familia.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('familia_alumno',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parentesco', sa.String(), nullable=True),
    sa.Column('responsable_principal', sa.Boolean(), nullable=False),
    sa.Column('recibe_comunicaciones', sa.Boolean(), nullable=False),
    sa.Column('familia_id', sa.Uuid(), nullable=False),
    sa.Column('alumno_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumno.id'], ),
    sa.ForeignKeyConstraint(['familia_id'], ['familia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ia_sugerencia',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('entidad', sa.String(), nullable=True),
    sa.Column('entidad_id', sa.Uuid(), nullable=True),
    sa.Column('contenido_generado', sa.String(), nullable=False),
    sa.Column('requiere_control_humano', sa.Boolean(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('fecha_generacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_revision', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('notificacion_template_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("estado IN ('pendiente_revision', 'aprobada', 'rechazada', 'ejecutada_automaticamente')", name='ck_ia_sugerencia_estado'),
    sa.CheckConstraint("tipo IN ('patron_detectado', 'comunicacion')", name='ck_ia_sugerencia_tipo'),
    sa.ForeignKeyConstraint(['notificacion_template_id'], ['notificacion_template.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_acceso',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('resultado', sa.String(), nullable=False),
    sa.Column('ip_origen', sa.String(), nullable=True),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("resultado IN ('exitoso', 'fallido')", name='ck_log_acceso_resultado'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orden_compra_detalle',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cantidad_pedida', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('orden_compra_id', sa.Uuid(), nullable=False),
    sa.Column('producto_servicio_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['orden_compra_id'], ['orden_compra.id'], ),
    sa.ForeignKeyConstraint(['producto_servicio_id'], ['producto_servicio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recepcion_compra',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('remito', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('orden_compra_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("tipo IN ('total', 'parcial')", name='ck_recepcion_compra_tipo'),
    sa.ForeignKeyConstraint(['orden_compra_id'], ['orden_compra.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regla_destinatario',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('destinatario_tipo', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('workflow_rule_id', sa.Uuid(), nullable=False),
    sa.Column('rol_id', sa.Uuid(), nullable=True),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("destinatario_tipo IN ('rol', 'usuario')", name='ck_regla_destinatario_tipo'),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['workflow_rule_id'], ['workflow_rule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('responsable_economico',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vigencia_desde', sa.Date(), nullable=False),
    sa.Column('vigencia_hasta', sa.Date(), nullable=True),
    sa.Column('fecha_solicitud_cambio', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('alumno_id', sa.Uuid(), nullable=False),
    sa.Column('familia_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumno.id'], ),
    sa.ForeignKeyConstraint(['familia_id'], ['familia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitud_compra',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('articulo', sa.String(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('area_solicitante', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('producto_servicio_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("estado IN ('pendiente', 'aprobada', 'rechazada')", name='ck_solicitud_compra_estado'),
    sa.ForeignKeyConstraint(['producto_servicio_id'], ['producto_servicio.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitud_inscripcion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ciclo_lectivo', sa.String(), nullable=False),
    sa.Column('etapa', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('fecha_solicitud', sa.Date(), nullable=False),
    sa.Column('fecha_resolucion', sa.Date(), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('aspirante_persona_id', sa.Uuid(), nullable=False),
    sa.Column('contacto_persona_id', sa.Uuid(), nullable=True),
    sa.Column('nivel_educativo_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("estado IN ('en_proceso', 'aprobada', 'rechazada', 'desistida')", name='ck_solicitud_inscripcion_estado'),
    sa.CheckConstraint("etapa IN ('consulta_lead', 'entrevista', 'postulacion', 'evaluacion_aprobacion', 'reserva_matricula', 'documentacion_contrato', 'inscripcion_confirmada')", name='ck_solicitud_inscripcion_etapa'),
    sa.ForeignKeyConstraint(['aspirante_persona_id'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['contacto_persona_id'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['nivel_educativo_id'], ['nivel_educativo.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_rol',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('rol_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documento_solicitud',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tipo_documento', sa.String(), nullable=False),
    sa.Column('archivo', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('fecha_carga', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('solicitud_inscripcion_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("estado IN ('pendiente', 'validado', 'rechazado')", name='ck_documento_solicitud_estado'),
    sa.ForeignKeyConstraint(['solicitud_inscripcion_id'], ['solicitud_inscripcion.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('etapa_solicitud',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('etapa', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('solicitud_inscripcion_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("estado IN ('en_proceso', 'completada', 'rechazada')", name='ck_etapa_solicitud_estado'),
    sa.CheckConstraint("etapa IN ('consulta_lead', 'entrevista', 'postulacion', 'evaluacion_aprobacion', 'reserva_matricula', 'documentacion_contrato', 'inscripcion_confirmada')", name='ck_etapa_solicitud_etapa'),
    sa.ForeignKeyConstraint(['solicitud_inscripcion_id'], ['solicitud_inscripcion.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inscripcion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ciclo_lectivo', sa.String(), nullable=False),
    sa.Column('fecha_inscripcion', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('alumno_id', sa.Uuid(), nullable=False),
    sa.Column('division_id', sa.Uuid(), nullable=False),
    sa.Column('solicitud_inscripcion_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("estado IN ('activa', 'finalizada', 'baja')", name='ck_inscripcion_estado'),
    sa.CheckConstraint("tipo IN ('nueva', 'reinscripcion', 'cambio_matricula', 'baja')", name='ck_inscripcion_tipo'),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumno.id'], ),
    sa.ForeignKeyConstraint(['division_id'], ['division.id'], ),
    sa.ForeignKeyConstraint(['solicitud_inscripcion_id'], ['solicitud_inscripcion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materia',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('anio_id', sa.Uuid(), nullable=False),
    sa.Column('division_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("tipo IN ('materia', 'taller')", name='ck_materia_tipo'),
    sa.ForeignKeyConstraint(['anio_id'], ['anio.id'], ),
    sa.ForeignKeyConstraint(['division_id'], ['division.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orden_compra_solicitud',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('orden_compra_id', sa.Uuid(), nullable=False),
    sa.Column('solicitud_compra_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['orden_compra_id'], ['orden_compra.id'], ),
    sa.ForeignKeyConstraint(['solicitud_compra_id'], ['solicitud_compra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recepcion_compra_detalle',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cantidad_recibida', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('recepcion_compra_id', sa.Uuid(), nullable=False),
    sa.Column('orden_compra_detalle_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['orden_compra_detalle_id'], ['orden_compra_detalle.id'], ),
    sa.ForeignKeyConstraint(['recepcion_compra_id'], ['recepcion_compra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_execution',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('intento', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('detalle', sa.String(), nullable=True),
    sa.Column('error_detail', sa.String(), nullable=True),
    sa.Column('workflow_rule_id', sa.Uuid(), nullable=False),
    sa.Column('event_log_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("estado IN ('exitoso', 'fallido', 'pendiente')", name='ck_workflow_execution_estado'),
    sa.ForeignKeyConstraint(['event_log_id'], ['event_log.id'], ),
    sa.ForeignKeyConstraint(['workflow_rule_id'], ['workflow_rule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asignacion_docente',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ciclo_lectivo', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('docente_id', sa.Uuid(), nullable=False),
    sa.Column('materia_id', sa.Uuid(), nullable=False),
    sa.Column('division_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['division.id'], ),
    sa.ForeignKeyConstraint(['docente_id'], ['docente.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['materia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asistencia',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('inscripcion_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("tipo IN ('presente', 'tardanza', 'ausente_pendiente', 'ausente_justificado', 'ausente_injustificado')", name='ck_asistencia_tipo'),
    sa.ForeignKeyConstraint(['inscripcion_id'], ['inscripcion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factura',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fecha_emision', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('inscripcion_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("estado IN ('pendiente', 'vencida', 'pagada')", name='ck_factura_estado'),
    sa.ForeignKeyConstraint(['inscripcion_id'], ['inscripcion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificacion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('destinatario_tipo', sa.String(), nullable=False),
    sa.Column('canal', sa.String(), nullable=False),
    sa.Column('destinatario_snapshot', sa.String(), nullable=False),
    sa.Column('asunto_snapshot', sa.String(), nullable=False),
    sa.Column('cuerpo_snapshot', sa.String(), nullable=False),
    sa.Column('estado_envio', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('workflow_execution_id', sa.Uuid(), nullable=False),
    sa.Column('familia_id', sa.Uuid(), nullable=True),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("destinatario_tipo IN ('familia', 'usuario')", name='ck_notificacion_destinatario_tipo'),
    sa.CheckConstraint("estado_envio IN ('enviado', 'fallido', 'pendiente')", name='ck_notificacion_estado_envio'),
    sa.ForeignKeyConstraint(['familia_id'], ['familia.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['workflow_execution_id'], ['workflow_execution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarea',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entidad', sa.String(), nullable=True),
    sa.Column('entidad_id', sa.Uuid(), nullable=True),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('prioridad', sa.String(), nullable=False),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_execution_id', sa.Uuid(), nullable=True),
    sa.Column('tarea_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("estado IN ('pendiente', 'en_progreso', 'completada', 'escalada')", name='ck_tarea_estado'),
    sa.CheckConstraint("prioridad IN ('baja', 'media', 'alta')", name='ck_tarea_prioridad'),
    sa.ForeignKeyConstraint(['tarea_id'], ['tarea.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['workflow_execution_id'], ['workflow_execution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle_factura',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('factura_id', sa.Uuid(), nullable=False),
    sa.Column('concepto_cobro_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['concepto_cobro_id'], ['concepto_cobro.id'], ),
    sa.ForeignKeyConstraint(['factura_id'], ['factura.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('justificacion_inasistencia',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('observacion', sa.String(), nullable=True),
    sa.Column('archivo', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('fecha_carga', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_resolucion', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('asistencia_id', sa.Uuid(), nullable=False),
    sa.Column('familia_id', sa.Uuid(), nullable=False),
    sa.Column('motivo_justificacion_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("estado IN ('pendiente', 'aprobada', 'rechazada')", name='ck_justificacion_inasistencia_estado'),
    sa.ForeignKeyConstraint(['asistencia_id'], ['asistencia.id'], ),
    sa.ForeignKeyConstraint(['familia_id'], ['familia.id'], ),
    sa.ForeignKeyConstraint(['motivo_justificacion_id'], ['motivo_justificacion.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pago',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('comprobante', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('referencia_transaccion', sa.String(), nullable=True),
    sa.Column('fecha_operacion', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('factura_id', sa.Uuid(), nullable=False),
    sa.Column('metodo_pago_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("estado IN ('aprobado', 'rechazado', 'pendiente')", name='ck_pago_estado'),
    sa.ForeignKeyConstraint(['factura_id'], ['factura.id'], ),
    sa.ForeignKeyConstraint(['metodo_pago_id'], ['metodo_pago.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimiento',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('observacion', sa.String(), nullable=True),
    sa.Column('cuenta_corriente_id', sa.Uuid(), nullable=False),
    sa.Column('concepto_cobro_id', sa.Uuid(), nullable=False),
    sa.Column('factura_id', sa.Uuid(), nullable=True),
    sa.Column('pago_id', sa.Uuid(), nullable=True),
    sa.Column('event_log_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("tipo IN ('debe', 'haber')", name='ck_movimiento_tipo'),
    sa.ForeignKeyConstraint(['concepto_cobro_id'], ['concepto_cobro.id'], ),
    sa.ForeignKeyConstraint(['cuenta_corriente_id'], ['cuenta_corriente.id'], ),
    sa.ForeignKeyConstraint(['event_log_id'], ['event_log.id'], ),
    sa.ForeignKeyConstraint(['factura_id'], ['factura.id'], ),
    sa.ForeignKeyConstraint(['pago_id'], ['pago.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_movimiento_cuenta_corriente_fecha', 'movimiento', ['cuenta_corriente_id', 'fecha'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_movimiento_cuenta_corriente_fecha', table_name='movimiento')
    op.drop_table('movimiento')
    op.drop_table('pago')
    op.drop_table('justificacion_inasistencia')
    op.drop_table('detalle_factura')
    op.drop_table('tarea')
    op.drop_table('notificacion')
    op.drop_table('factura')
    op.drop_table('asistencia')
    op.drop_table('asignacion_docente')
    op.drop_table('workflow_execution')
    op.drop_table('recepcion_compra_detalle')
    op.drop_table('orden_compra_solicitud')
    op.drop_table('materia')
    op.drop_table('inscripcion')
    op.drop_table('etapa_solicitud')
    op.drop_table('documento_solicitud')
    op.drop_table('usuario_rol')
    op.drop_table('solicitud_inscripcion')
    op.drop_table('solicitud_compra')
    op.drop_table('responsable_economico')
    op.drop_table('regla_destinatario')
    op.drop_table('recepcion_compra')
    op.drop_table('orden_compra_detalle')
    op.drop_table('log_acceso')
    op.drop_table('ia_sugerencia')
    op.drop_table('familia_alumno')
    op.drop_table('excepcion_vencimiento')
    op.drop_index('ix_event_log_estado_timestamp', table_name='event_log')
    op.drop_table('event_log')
    op.drop_table('division')
    op.drop_table('cuenta_corriente')
    op.drop_index('ix_audit_log_entidad_entidad_id_fecha', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('workflow_rule')
    op.drop_table('usuario')
    op.drop_table('rol_permiso')
    op.drop_table('regla_penalidad')
    op.drop_table('producto_proveedor')
    op.drop_table('precio_producto')
    op.drop_table('orden_compra')
    op.drop_table('familia')
    op.drop_table('docente')
    op.drop_table('campo_evento')
    op.drop_table('anio')
    op.drop_table('alumno')
    op.drop_table('tipo_evento')
    op.drop_table('rol')
    op.drop_table('proveedor')
    op.drop_table('producto_servicio')
    op.drop_table('persona')
    op.drop_table('permiso')
    op.drop_table('notificacion_template')
    op.drop_table('nivel_educativo')
    op.drop_table('motivo_justificacion')
    op.drop_table('metodo_pago')
    op.drop_table('concepto_cobro')
    # ### end Alembic commands ###
