"""agregar reglas recurrentes de facturacion

Revision ID: 7df41b8dcf59
Revises: fd442e4d41af
Create Date: 2026-08-31 13:54:46.205743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7df41b8dcf59'
down_revision: Union[str, Sequence[str], None] = 'fd442e4d41af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ejecucion_facturacion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('periodo', sa.Date(), nullable=False),
    sa.Column('fecha_ejecucion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('facturas_generadas', sa.Integer(), nullable=False),
    sa.Column('cargos_generados', sa.Integer(), nullable=False),
    sa.Column('cargos_omitidos', sa.Integer(), nullable=False),
    sa.Column('cargos_bloqueados', sa.Integer(), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ejecucion_facturacion_periodo', 'ejecucion_facturacion', ['periodo'], unique=False)
    op.create_table('regla_facturacion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('ciclo_lectivo', sa.String(), nullable=False),
    sa.Column('importe', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('periodicidad', sa.String(), nullable=False),
    sa.Column('vigencia_desde', sa.Date(), nullable=False),
    sa.Column('vigencia_hasta', sa.Date(), nullable=False),
    sa.Column('mes_aplicacion', sa.Integer(), nullable=True),
    sa.Column('dia_vencimiento', sa.Integer(), nullable=False),
    sa.Column('criterio_aplicacion', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('concepto_cobro_id', sa.Uuid(), nullable=False),
    sa.Column('nivel_educativo_id', sa.Uuid(), nullable=True),
    sa.Column('anio_id', sa.Uuid(), nullable=True),
    sa.Column('division_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("criterio_aplicacion IN ('todas_inscripciones', 'nivel', 'anio', 'division')", name='ck_regla_facturacion_criterio'),
    sa.CheckConstraint("estado IN ('borrador', 'activa', 'pausada', 'finalizada')", name='ck_regla_facturacion_estado'),
    sa.CheckConstraint("periodicidad IN ('mensual', 'anual')", name='ck_regla_facturacion_periodicidad'),
    sa.ForeignKeyConstraint(['anio_id'], ['anio.id'], ),
    sa.ForeignKeyConstraint(['concepto_cobro_id'], ['concepto_cobro.id'], ),
    sa.ForeignKeyConstraint(['division_id'], ['division.id'], ),
    sa.ForeignKeyConstraint(['nivel_educativo_id'], ['nivel_educativo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_regla_facturacion_ciclo_estado', 'regla_facturacion', ['ciclo_lectivo', 'estado'], unique=False)
    op.create_table('cargo_facturacion_generado',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('periodo', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('importe', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('regla_facturacion_id', sa.Uuid(), nullable=False),
    sa.Column('ejecucion_facturacion_id', sa.Uuid(), nullable=False),
    sa.Column('factura_id', sa.Uuid(), nullable=False),
    sa.Column('inscripcion_id', sa.Uuid(), nullable=False),
    sa.Column('concepto_cobro_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['concepto_cobro_id'], ['concepto_cobro.id'], ),
    sa.ForeignKeyConstraint(['ejecucion_facturacion_id'], ['ejecucion_facturacion.id'], ),
    sa.ForeignKeyConstraint(['factura_id'], ['factura.id'], ),
    sa.ForeignKeyConstraint(['inscripcion_id'], ['inscripcion.id'], ),
    sa.ForeignKeyConstraint(['regla_facturacion_id'], ['regla_facturacion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inscripcion_id', 'concepto_cobro_id', 'periodo', name='uq_cargo_facturacion_generado_inscripcion_concepto_periodo')
    )
    op.create_index('ix_cargo_facturacion_generado_periodo', 'cargo_facturacion_generado', ['periodo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cargo_facturacion_generado_periodo', table_name='cargo_facturacion_generado')
    op.drop_table('cargo_facturacion_generado')
    op.drop_index('ix_regla_facturacion_ciclo_estado', table_name='regla_facturacion')
    op.drop_table('regla_facturacion')
    op.drop_index('ix_ejecucion_facturacion_periodo', table_name='ejecucion_facturacion')
    op.drop_table('ejecucion_facturacion')
    # ### end Alembic commands ###
