"""auth: log_acceso.usuario_id nullable + unique en usuario.email

Revision ID: 8c54bb722fc1
Revises: 7ba0cd6025cc
Create Date: 2026-08-27 23:37:09.044139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c54bb722fc1'
down_revision: Union[str, Sequence[str], None] = '7ba0cd6025cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Un intento de login con un email inexistente no tiene usuario al que apuntar (RF-27).
    op.alter_column('log_acceso', 'usuario_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    # Falla si ya hay filas con usuario_id NULL: borrarlas antes de bajar esta revisión.
    op.alter_column('log_acceso', 'usuario_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
