"""auth: unique en rol.nombre, usuario_rol y rol_permiso

Revision ID: 9b8fc5e775c0
Revises: 8c54bb722fc1
Create Date: 2026-08-28 11:56:39.030988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b8fc5e775c0'
down_revision: Union[str, Sequence[str], None] = '8c54bb722fc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_rol_nombre', 'rol', ['nombre'])
    op.create_unique_constraint('uq_rol_permiso_rol_id_permiso_id', 'rol_permiso', ['rol_id', 'permiso_id'])
    op.create_unique_constraint('uq_usuario_rol_usuario_id_rol_id', 'usuario_rol', ['usuario_id', 'rol_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_usuario_rol_usuario_id_rol_id', 'usuario_rol', type_='unique')
    op.drop_constraint('uq_rol_permiso_rol_id_permiso_id', 'rol_permiso', type_='unique')
    op.drop_constraint('uq_rol_nombre', 'rol', type_='unique')
    # ### end Alembic commands ###
