"""registrar usuario de pago

Revision ID: a6710c3f0920
Revises: a9aa39383042
Create Date: 2026-08-31 21:08:22.705380

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a6710c3f0920"
down_revision: str | Sequence[str] | None = "a9aa39383042"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pago", sa.Column("usuario_registro_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(None, "pago", "usuario", ["usuario_registro_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "pago", type_="foreignkey")
    op.drop_column("pago", "usuario_registro_id")
    # ### end Alembic commands ###
