"""agregar comprobantes de pago

Revision ID: a9aa39383042
Revises: 70743ef2902c
Create Date: 2026-08-31 21:04:00.724613

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a9aa39383042"
down_revision: str | Sequence[str] | None = "70743ef2902c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "archivo_comprobante_pago",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("tipo_contenido", sa.String(), nullable=False),
        sa.Column("tamanio", sa.Integer(), nullable=False),
        sa.Column("contenido", sa.LargeBinary(), nullable=False),
        sa.Column("pago_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pago_id"],
            ["pago.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pago_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("archivo_comprobante_pago")
    # ### end Alembic commands ###
