"""workflows agrega integridad a plantillas y destinatarios

Revision ID: bcfb712e3a60
Revises: f912c5af849e
Create Date: 2026-10-01 02:10:25.630089

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bcfb712e3a60"
down_revision: Union[str, Sequence[str], None] = "f912c5af849e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_notificacion_template_nombre", "notificacion_template", ["nombre"]
    )
    op.create_unique_constraint(
        "uq_regla_destinatario_regla_rol",
        "regla_destinatario",
        ["workflow_rule_id", "rol_id"],
    )
    op.create_unique_constraint(
        "uq_regla_destinatario_regla_usuario",
        "regla_destinatario",
        ["workflow_rule_id", "usuario_id"],
    )
    op.create_check_constraint(
        "ck_regla_destinatario_referencia",
        "regla_destinatario",
        "(destinatario_tipo = 'rol' AND rol_id IS NOT NULL AND usuario_id IS NULL) "
        "OR (destinatario_tipo = 'usuario' AND usuario_id IS NOT NULL AND rol_id IS NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_regla_destinatario_referencia", "regla_destinatario", type_="check"
    )
    op.drop_constraint(
        "uq_regla_destinatario_regla_usuario", "regla_destinatario", type_="unique"
    )
    op.drop_constraint(
        "uq_regla_destinatario_regla_rol", "regla_destinatario", type_="unique"
    )
    op.drop_constraint(
        "uq_notificacion_template_nombre", "notificacion_template", type_="unique"
    )
    # ### end Alembic commands ###
