"""agregar parentesco de contacto a admision

Revision ID: f3258843c61f
Revises: 2abdec1fcb72
Create Date: 2026-09-07 01:38:40.620772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3258843c61f'
down_revision: Union[str, Sequence[str], None] = '2abdec1fcb72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitud_inscripcion', sa.Column('contacto_parentesco', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solicitud_inscripcion', 'contacto_parentesco')
    # ### end Alembic commands ###
