"""factura cristaliza responsable economico

Revision ID: fd442e4d41af
Revises: 37d7c3b1f8a2
Create Date: 2026-08-31 00:58:53.048650

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fd442e4d41af"
down_revision: str | Sequence[str] | None = "37d7c3b1f8a2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("factura", sa.Column("responsable_economico_id", sa.Uuid(), nullable=False))
    op.create_foreign_key(
        "fk_factura_responsable_economico",
        "factura",
        "responsable_economico",
        ["responsable_economico_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_factura_responsable_economico", "factura", type_="foreignkey")
    op.drop_column("factura", "responsable_economico_id")
    # ### end Alembic commands ###
